// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package deeplink.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import deeplink.proxies.microflows.Microflows;
import deeplink.utils.DeeplinkUtils;

/**
 * Creates a deeplink configuration using DeepLinkname as identifier.
 * Any existing configurations with this identifier will be deleted.
 */
public class SetStringParameterDeeplink extends CustomJavaAction<java.lang.Void>
{
	private final java.lang.String Microflow;
	private final java.lang.String Description;
	private final java.lang.String DeepLinkName;
	private final java.lang.Boolean ForceLogin;
	private final java.lang.Boolean KeepAsHomeDeeplink;

	public SetStringParameterDeeplink(
		IContext context,
		java.lang.String _microflow,
		java.lang.String _description,
		java.lang.String _deepLinkName,
		java.lang.Boolean _forceLogin,
		java.lang.Boolean _keepAsHomeDeeplink
	)
	{
		super(context);
		this.Microflow = _microflow;
		this.Description = _description;
		this.DeepLinkName = _deepLinkName;
		this.ForceLogin = _forceLogin;
		this.KeepAsHomeDeeplink = _keepAsHomeDeeplink;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		DeeplinkUtils.updateOrCreateDeeplink(getContext(), DeepLinkName, ForceLogin, Description, Microflow, KeepAsHomeDeeplink, null, null);
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetStringParameterDeeplink";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
