// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package email_connector.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import java.io.InputStream;

public class CopyAttachmentContent extends CustomJavaAction<java.lang.Boolean>
{
	/** @deprecated use CopyFrom.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __CopyFrom;
	private final system.proxies.FileDocument CopyFrom;
	/** @deprecated use CopyTo.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __CopyTo;
	private final system.proxies.FileDocument CopyTo;

	public CopyAttachmentContent(
		IContext context,
		IMendixObject _copyFrom,
		IMendixObject _copyTo
	)
	{
		super(context);
		this.__CopyFrom = _copyFrom;
		this.CopyFrom = _copyFrom == null ? null : system.proxies.FileDocument.initialize(getContext(), _copyFrom);
		this.__CopyTo = _copyTo;
		this.CopyTo = _copyTo == null ? null : system.proxies.FileDocument.initialize(getContext(), _copyTo);
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
        IContext context = this.getContext();

        try (InputStream filedocumentObj = Core.getFileDocumentContent(this.getContext(), this.CopyFrom.getMendixObject())) {
            String filename = this.CopyFrom.getName();
            Core.storeFileDocumentContent(context, this.CopyTo.getMendixObject(), filename, filedocumentObj);
        }

        return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CopyAttachmentContent";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
