// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package email_connector.actions;

import com.mendix.core.Core;
import com.mendix.core.objectmanagement.member.MendixString;
import com.mendix.datahub.connector.email.utils.EmailConnectorException;
import com.mendix.datahub.connector.email.utils.Error;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObjectMember;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import email_connector.implementation.MxMailMapper;
import mxmodelreflection.TokenReplacer;
import java.util.List;
import java.util.Map;

public class CreateEmailFromTemplate extends CustomJavaAction<IMendixObject>
{
	private final IMendixObject DataObject;
	/** @deprecated use EmailTemplate.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __EmailTemplate;
	private final email_connector.proxies.EmailTemplate EmailTemplate;
	private final java.lang.Boolean Queued;

	public CreateEmailFromTemplate(
		IContext context,
		IMendixObject _dataObject,
		IMendixObject _emailTemplate,
		java.lang.Boolean _queued
	)
	{
		super(context);
		this.DataObject = _dataObject;
		this.__EmailTemplate = _emailTemplate;
		this.EmailTemplate = _emailTemplate == null ? null : email_connector.proxies.EmailTemplate.initialize(getContext(), _emailTemplate);
		this.Queued = _queued;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		if (this.EmailTemplate == null)
			throw new EmailConnectorException(Error.EMPTY_EMAIL_TEMPLATE.getMessage());

		List<IMendixObject> tokenList = Core.retrieveByPath(getContext(), this.EmailTemplate.getMendixObject(), email_connector.proxies.EmailTemplate.MemberNames.EmailTemplate_Token.toString());
		var emailMessageFromTemplate = MxMailMapper.getEmailMessageFromTemplate(getContext(), this.EmailTemplate, this.Queued);

		Map<String, ? extends IMendixObjectMember<?>> members = emailMessageFromTemplate.getMendixObject().getMembers(getContext());
		for (Map.Entry<String, ? extends IMendixObjectMember<?>> entry : members.entrySet()) {
			IMendixObjectMember<?> m = entry.getValue();
			if (m instanceof MendixString && m.hasWriteAccess(this.getContext())) {
				MendixString member = (MendixString) m;
				member.setValue(this.getContext(), TokenReplacer.replaceTokens(this.getContext(), member.getValue(this.getContext()), tokenList, this.DataObject));
			}
		}
		return emailMessageFromTemplate.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CreateEmailFromTemplate";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
