// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package email_connector.actions;

import com.mendix.datahub.connector.email.model.autoconfig.AutoConfiguration;
import com.mendix.datahub.connector.email.utils.EmailConnectorException;
import com.mendix.datahub.connector.email.utils.Error;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import email_connector.implementation.MxMailMapper;

public class GetAutoConfig extends CustomJavaAction<IMendixObject>
{
	private final java.lang.String EmailID;

	public GetAutoConfig(
		IContext context,
		java.lang.String _emailID
	)
	{
		super(context);
		this.EmailID = _emailID;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		if (this.EmailID == null || this.EmailID.isBlank())
			throw new EmailConnectorException(Error.EMPTY_EMAIL_ID.getMessage());
        var emailProviders = AutoConfiguration.getEmailProvider(this.EmailID);
        var mxEmailProvider = new email_connector.proxies.EmailProvider(getContext());
        MxMailMapper.getMappedEmailProvider(getContext(), emailProviders, mxEmailProvider);
        return mxEmailProvider.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetAutoConfig";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
