// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";
import "./html2canvas.min.js";
import html2canvas from "./html2canvas.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} name
 * @returns {Promise.<string>}
 */
export async function JavaScript_Capture(name) {
	// BEGIN USER CODE
	debugger;
	var targetClass =`.${name}`;
	var chart =document.querySelector(targetClass);
	return new Promise(function (resolve){
	if(chart){
	//GetDataURL
	html2canvas(chart).then(canvas => {
	var encodedURL = canvas.toDataURL();
	var substractedURL=encodedURL.substring(encodedURL.indexOf(',')+1);
    return resolve(substractedURL);});
	}
	else {return resolve("")}
	})


	//throw new Error("JavaScript action was not implemented");
	// END USER CODE
}
