// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package jxlser.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import jxlser.implementation.JxlserParameterUtil;

/**
 * Specifies a context parameter object to merge into the template.
 */
public class AddJxlsContextParameter extends CustomJavaAction<java.lang.Boolean>
{
	private final java.lang.String ContextParameterName;
	private final IMendixObject ContextParameter;

	public AddJxlsContextParameter(
		IContext context,
		java.lang.String _contextParameterName,
		IMendixObject _contextParameter
	)
	{
		super(context);
		this.ContextParameterName = _contextParameterName;
		this.ContextParameter = _contextParameter;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		JxlserParameterUtil.addParameter(ContextParameterName, ContextParameter);
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "AddJxlsContextParameter";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
