// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package jxlser.actions;

import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import jxlser.implementation.JxlserProcessor;

/**
 * Generates an Excel file by merging the specified context parameters and template file. Store the template file in the project's resource folder and specify its path.
 */
public class ProcessJxlsTemplateByResourcePath extends CustomJavaAction<java.lang.Boolean>
{
	private final java.lang.String TemplateFilePath;
	/** @deprecated use MergedXlsFile.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __MergedXlsFile;
	private final system.proxies.FileDocument MergedXlsFile;

	public ProcessJxlsTemplateByResourcePath(
		IContext context,
		java.lang.String _templateFilePath,
		IMendixObject _mergedXlsFile
	)
	{
		super(context);
		this.TemplateFilePath = _templateFilePath;
		this.__MergedXlsFile = _mergedXlsFile;
		this.MergedXlsFile = _mergedXlsFile == null ? null : system.proxies.FileDocument.initialize(getContext(), _mergedXlsFile);
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		try (InputStream is = new FileInputStream(
				Core.getConfiguration().getResourcesPath() + System.getProperty("file.separator") + TemplateFilePath)) {
			JxlserProcessor.doProcessTemplate(getContext(), is, MergedXlsFile, null);
		} catch (IOException e) {
			throw e;
		}
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ProcessJxlsTemplateByResourcePath";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
