// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package jxlser.actions;

import java.util.TimeZone;
import org.apache.poi.util.LocaleUtil;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 * Sets the timezone when the POI handles datetime.
 * 
 */
public class SetUserTimeZone extends CustomJavaAction<java.lang.Void>
{
	private final java.lang.String TimezoneId;

	public SetUserTimeZone(
		IContext context,
		java.lang.String _timezoneId
	)
	{
		super(context);
		this.TimezoneId = _timezoneId;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		LocaleUtil.setUserTimeZone(TimeZone.getTimeZone(TimezoneId));
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetUserTimeZone";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
